"""
JODOHKU.MY — Service Stubs
Implementation placeholders for all business logic services.
Each service encapsulates its domain logic — swap implementations without changing routes.
"""

# ═══════════════════════════════════════
#  PROFILE SERVICE
# ═══════════════════════════════════════

class ProfileService:
    def __init__(self, db): self.db = db
    async def get_profile(self, user_id, viewer_id=None): ...
    async def get_profile_by_code(self, code_name, viewer_id=None, viewer_tier=None): ...
    async def update_profile(self, user_id, data): ...
    async def get_preferences(self, user_id): ...
    async def update_preferences(self, user_id, data): ...
    async def get_completion_breakdown(self, user_id): ...
    async def submit_t20_verification(self, user_id, file, doc_type): ...


class PhotoService:
    def __init__(self, db): self.db = db
    async def upload_photo(self, user_id, photo_type, file): ...
    async def delete_photo(self, user_id, photo_id): ...
    async def reorder(self, user_id, photo_id, new_order): ...


class QuizService:
    def __init__(self, db): self.db = db
    async def get_questions(self, user_id, batch): ...
    async def submit_answer(self, user_id, question_id, score, time_taken): ...
    async def submit_batch(self, user_id, answers): ...
    async def get_score(self, user_id): ...
    async def get_progress(self, user_id): ...


class ChatService:
    def __init__(self, db): self.db = db
    async def get_conversations(self, user_id, tier, status, page): ...
    async def get_messages(self, user_id, conversation_id, before, limit): ...
    async def send_message(self, sender_id, conversation_id, content, is_ice_breaker, sender_tier): ...
    async def initiate_conversation(self, initiator_id, target_id, first_message, is_ice_breaker, initiator_tier): ...
    async def get_ice_breakers(self): ...
    async def handle_whatsapp_request(self, user_id, conversation_id, action, user_tier): ...
    async def record_strike(self, user_id, reason): ...
    async def register_ws_connection(self, user_id, websocket): ...
    async def unregister_ws_connection(self, user_id): ...
    async def handle_ws_message(self, user_id, data): ...
    async def handle_ws_read(self, user_id, data): ...
    async def broadcast_typing(self, user_id, conversation_id, is_typing): ...


class PaymentService:
    def __init__(self, db): self.db = db
    async def create_bill(self, user_id, tier, promo_code=None): ...
    async def process_callback(self, gateway, data): ...
    async def get_user_transactions(self, user_id): ...
    async def request_refund(self, user_id, reason=None): ...


class SubscriptionService:
    def __init__(self, db): self.db = db
    async def get_all_plans(self): ...
    async def get_active_subscription(self, user_id): ...
    async def get_golden_tickets(self, user_id): ...
    async def redeem_golden_ticket(self, user_id, code): ...


class NotificationService:
    def __init__(self, db): self.db = db
    async def get_notifications(self, user_id, page, unread_only): ...
    async def mark_read(self, user_id, notification_id): ...
    async def mark_all_read(self, user_id): ...
    async def get_unread_count(self, user_id): ...
    async def update_preferences(self, user_id, preferences): ...
    async def send_notification(self, user_id, type, title_ms, title_en, body_ms, body_en, data=None): ...


class WaliService:
    def __init__(self, db): self.db = db
    async def send_invitation(self, user_id, wali_email, wali_name, relation): ...
    async def get_status(self, user_id): ...
    async def toggle_mode(self, user_id, enabled): ...
    async def revoke_access(self, user_id, invitation_id): ...
    async def wali_login(self, email, password, token): ...
    async def get_wali_dashboard(self, user_id): ...


class AccountService:
    def __init__(self, db): self.db = db
    async def mark_married(self, user_id): ...
    async def pause_account(self, user_id): ...
    async def unpause_account(self, user_id): ...
    async def request_deletion(self, user_id): ...
    async def change_password(self, user_id, current_password, new_password): ...
    async def block_user(self, user_id, target_user_id): ...


class ReportService:
    def __init__(self, db): self.db = db
    async def create_report(self, reporter_id, reported_user_id, category, description): ...


class AdminService:
    def __init__(self, db): self.db = db
    async def get_dashboard_metrics(self): ...
    async def get_revenue_report(self, period): ...
    async def list_users(self, search, status, tier, page): ...
    async def suspend_user(self, user_id, reason, duration_hours, admin_id): ...
    async def kill_switch(self, user_id, reason, admin_id): ...
    async def list_reports(self, status, category, page): ...
    async def resolve_report(self, report_id, resolution, admin_notes, admin_id): ...
    async def get_report_chat_log(self, report_id): ...
    async def list_pending_asnaf(self): ...
    async def approve_asnaf(self, application_id, admin_notes, admin_id): ...
    async def reject_asnaf(self, application_id, admin_notes, admin_id): ...
    async def list_pending_t20(self): ...
    async def approve_t20(self, user_id, admin_id): ...
    async def list_transactions(self, gateway, status, page): ...
    async def get_active_subscriptions_by_tier(self): ...
    async def trace_watermark(self, image_hash): ...
    async def get_audit_log(self, page): ...


class EKYCService:
    def __init__(self, db): self.db = db
    async def create_verification_session(self, request): ...
    async def process_callback(self, data): ...
